### ISSUE TITLE
movin ferward, backin up 

### ISSUE THREAD

**Issue by lb2410** [edwardsharp/lorenebouboushian.org#2]
requests for @edwardsharp 

Front page:
Change _"[[collaborative_ performance artist]]" to collaborative performance artist” then under it “see below for upcoming engagements”
Photos that scroll automatically?

also i added a 'writing' page but i can't remember how you told me to add that to the menu

i also don' know how to get to the site itself, since i closed the tab and lorenebouboushian.org takes me to the old domain on wordpress.

**Comment by edwardsharp** [comment]
@lb2410 the url is, at the moment: https://edwardsharp.github.io/lorenebouboushian.org/

**Comment by edwardsharp** [comment]
@lb2410 also, for the `writing` page, you need something like this at the top: 

```
---
layout: page
name: THE NAME OF YOUR PAGE
position: 1
---
```

the instructions are in the `README` file which can be seen here: https://github.com/edwardsharp/lorenebouboushian.org#directories
