### ISSUE TITLE
lots of stuff 

### ISSUE THREAD

**Issue by lb2410** [edwardsharp/lorenebouboushian.org#3]
hi @edwardsharp 
First off i should say i wanted to do this because wordpress becomes littered with ads. So if the same thing is gonna happen to this site, fuck i’ve wasted a lot of time learning all this

Front page: i am asking you to do this because i don’t know how to change stuff on the front page and can’t for the life of me figure out how
Change to “collaborative performance artist” then under it “see below for upcoming engagements”
Photos that scroll automatically?
Put the menu on top?

Black background for whole site

How do i format the text beyond headers and emphasis? Like i want to center stuff on the SELECTED PROJECTS page, for example

Speaking of the selected projects page--i added new stuff to it and to writing and now when i click on them they’re asking me to open a file...made the page names .md to fix it so maybe it’s not showing up because i did too many commits today?

Writing:
I’d like to link to a couple different pages for hellfired, food stamps, and extent writing (as opposed to writing being on the page itself)

I’ll bug you about transferring the domain name soon

**Comment by lb2410** [comment]
nevermind about the pages opening to files, it workin now

**Comment by edwardsharp** [comment]
@lb2410 no, there's no ads. while i can't be certain about the future you should feel confidant that github pages will not start putting ads in yr shit.

FWIW, you can use the search box at the top of this page to look for strings of text like "collaborative performance artist" to find out which file it's in and then change the text in the file. in this case it's this one: https://github.com/edwardsharp/lorenebouboushian.org/blob/master/_includes/header.html#L27 

i can fix these things. all of them are simple but the photo carousel ("photos that scroll automatically") thing is a little more complex but not impossible. am working on them now, more soon.

**Comment by lb2410** [comment]
cool. you can use the photos i added today for the carousel on the home page. and yeah--menu at the top would be great too.

also, it would be great to know how to Make the tabs look like this: Press | Lorene Bouboushian
(so it's not just press and the line with nothing after it)

otherwise it's just the formatting question for the projects page and the links on the writing page.

**Comment by edwardsharp** [comment]
@lb2410 like you want the tab that says `Press` to read `Press | Lorene Bouboushian`? if so then just use double-quotes " in the top of the press page .md file so like:
```md
---
layout: page
name: "Press | Lorene Bouboushian"
position: 6
---
```

or something else? i don't quite understand

> (so it's not just press and the line with nothing after it)

...sometimes the `Press` link or whatever is the last link in the nav (tabs) will be on it's own line depending on how wide the window of the browser viewing the page is... is that what you mean? if so, just re-size the browser window 😸

**Comment by edwardsharp** [comment]
also, @lb2410 keep in mind that there are now two github repositories for your site:
https://github.com/edwardsharp/lorenebouboushian.org
and
https://github.com/lb2410/lorenebouboushian.org

you recently made changes to the one in my github account (https://github.com/edwardsharp/lorenebouboushian.org) and that's chill but when your lorenebouboushian.org domain gets setup it will point at your github user's repository (https://github.com/lb2410/lorenebouboushian.org). don't despair-- it's very easy to sync any changes between the two.

**Comment by edwardsharp** [comment]
@lb2410 well, after we do the last step of configuring your domain to point at your github pages repository then i will delete the repository in my account so there's just the one in your account-- so then from that point forward you can just make changes there. for the time being, just make edits to the one here, in my account.

**Comment by edwardsharp** [comment]
ohey @lb2410 i added a photo carousel: https://edwardsharp.github.io/lorenebouboushian.org/

you can add/upload images to the [/assets/images/carousel/](https://github.com/edwardsharp/lorenebouboushian.org/tree/master/assets/images/carousel) directory. note that images are displayed in alpha/numeric order so you can name yr images like `0.jpg` `1.png` `666.gif` and so on.

**Comment by lb2410** [comment]
hey thanks for working on this. 

so, auto scroll--as in not having to press a button for the photos to move. possible?

also, i uploaded more than 2 fotos on friday, that's what i was referring to. but now i can't find them.
